name: ehforwarderbot_docs
channels:
- conda-forge
dependencies:
- python>=3.6
- pandoc
- sphinx>=1.5.1
- pip
- pip:
  - sphinxcontrib-restbuilder
  - sphinx-autodoc-typehints
  - sphinx-intl
  - ruamel.yaml
  - bullet
  - cjkwrap
  - typing_extensions
#  - sphinx-readable-theme
